- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Refactored storage interfaces and implemented placeholder methods for ClickHouse connector.
- Introduced new interfaces `IStorage`, `IStorageBase`, `IStorageCache`, and `IStorageDB` in `connector.go`.
- Updated `NewStorageConnector` function to return `IStorage` instead of `StorageConnector`.
- Added placeholder methods for ClickHouse connector in `clickhouse.go`: `query`, `insert`, `delete`, `queryCache`, `purgeCache`, and `setCache`.
- Renamed methods in `memory.go` to align with new interface: `Set` to `setCache`, `Get` to `queryCache`, and `Delete` to `purgeCache`.
1. Ensure all existing tests pass after the refactoring.
2. Verify that the memory connector still functions correctly with the renamed methods.
3. Check that the ClickHouse connector can be initialized without errors.
4. …
> Implement IStorage Factory to interact with cache and DB connectors

- internal/orchestrator/failure_recoverer.go
- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/worker/worker.go
Refactored the worker, poller, and failure recoverer to improve concurrency and error handling.
- Introduced a new `Worker.Run()` method that processes multiple blocks concurrently.
- Updated `Poller` and `FailureRecoverer` to use the new `Worker.Run()` method.
- Removed individual goroutines for each block in favor of a more efficient batch processing approach.
- Introduced a `BlockResult` struct to encapsulate the results of processing a block.
- Improved error handling and reporting for block processing failures.
- Refactored `getBlockRange()` to return a slice of block numbers instead of start and end blocks.
- Removed the `triggerWorker()` method from both `Poller` and `FailureRecoverer`.
- Updated the `handleBlockFailures()` and `handleBlockResults()` methods to process batch …
> Refactor worker to process multiple blocks concurrently

- internal/storage/connector.go
- internal/storage/memory.go
Implemented DBStorage interface for MemoryConnector and updated NewStorageConnector function.
- Added DBStorage interface implementation to MemoryConnector
- Implemented methods for inserting and retrieving blocks, transactions, and events
- Added a method to get the maximum block number
- Updated NewStorageConnector to use MemoryConnector for both OrchestratorStorage and DBStorage
This change extends the functionality of the MemoryConnector to support both OrchestratorStorage and DBStorage interfaces. It allows for in-memory storage and retrieval of blockchain data, which can be useful for testing and development purposes without the need for a separate database.
> Implement memory storage for blocks, transactions, and events

- internal/common/rpc.go
- internal/orchestrator/poller.go
- internal/storage/memory.go
- internal/worker/serializer.go
Added ability to set block limit for polling. Added additional logging for RPC method support checks and added safeguards for block data serialization.
- Added logging for RPC method support checks in `rpc.go`
- Introduced `POLL_UNTIL_BLOCK` environment variable to limit polling
- Modified block range calculation to prevent skipping the genesis block
- Updated `GetLatestPolledBlockNumber` to return `math.MaxUint64` when no block is found so next block polled will overflow to genesis
- Added a null check for `WithdrawalsHash` in block serialization
1. Set the `POLL_UNTIL_BLOCK` environment variable to test polling limits
2. Verify logging output for RPC method support checks
3. Ensure polling starts from genesis when no last polled block is found
4. Test block serialization with and …
> Add debug logging and enhance block polling logic

- internal/orchestrator/commiter.go
- internal/orchestrator/orchestrator.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Refactored storage system to support multiple storage instances and improved query filtering.
Note that intellisense won't show it if a storageConnector is not implementing the needed interface. But it will throw at runtime. This change was made to not have the switch clause duplicated. If that's not important, we can create multiple functions (one for each interface) so that editors can understand type inference
- Introduced `StorageConfig` with separate configurations for Main, Staging, and Orchestrator storage.
- Added `QueryFilter` struct for more flexible querying of blocks, transactions, and events.
- Updated `IStorage` interface to include separate storage instances for different purposes.
- Modified `NewStorageConnector` to create multiple storage instances based on the new …
> Refactor storage interface and implement query filtering

- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Implemented ClickHouse database operations for blocks, transactions, and logs.
- Added `Table` field to `ClickhouseConnectorConfig` struct
- Implemented `InsertBlocks`, `InsertTransactions`, and `InsertLogs` methods for ClickHouseConnector
- Renamed `InsertEvents` to `InsertLogs` in the `IDBStorage` interface and `MemoryConnector`
- Updated `ClickHouseConnector` struct to store the configuration
- Implemented `GetBlocks`, `GetTransactions`, and `GetEvents` methods for data retrieval
- Added `StoreBlockFailures`, `GetBlockFailures`, and `DeleteBlockFailures` methods for handling block processing failures
- Implemented `StoreLatestPolledBlockNumber` and `GetLatestPolledBlockNumber` for tracking indexing progress
- Added `GetMaxBlockNumber` method to retrieve the highest block number stored …
> clickhouse-storage-functions

- internal/storage/connector.go
- internal/storage/memory.go
Renamed 'events' to 'logs' for consistency and clarity in storage-related functions.
- Renamed parameter 'events' to 'logs' in `InsertLogs` function
- Changed `GetEvents` function to `GetLogs`
- Updated variable names from 'events' to 'logs' in affected functions
- Modified function signatures in the `IDBStorage` interface to reflect these changes
1. Ensure all calls to `InsertLogs` now use 'logs' instead of 'events' as the parameter name
2. Verify that `GetLogs` is called instead of `GetEvents` throughout the codebase
3. Check that the `IDBStorage` interface is implemented correctly in all storage connectors
4. Run existing tests to confirm that the functionality remains unchanged
This change improves code consistency and readability by using the term 'logs' instead of 'events' when …
> unify-logs-naming-with-db

- internal/orchestrator/commiter.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Renamed "events" to "logs" throughout the codebase for consistency and clarity.
- Updated function names and variables in `commiter.go`, `clickhouse.go`, `connector.go`, and `memory.go` files.
- Replaced "event" with "log" in variable names, function parameters, and comments.
- Modified database queries and cache keys to use "log" instead of "event".
- Updated the `DeleteLogs` function to include `BlockNumber` in the deletion criteria.
1. Run unit tests for the affected files to ensure functionality remains intact.
2. Test the storage operations (insert, get, delete) for logs in both ClickHouse and memory storage.
3. Verify that the orchestrator correctly handles log data throughout its lifecycle.
4. Check that existing queries and data manipulations still work as expected with the new …
> fixed delete logs and renaming

- internal/common/block.go
- internal/orchestrator/commiter.go
- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Created a separate interface for staging storage.
Introduced a new `BlockData` structure and refactored the committer and poller to use it, improving data handling efficiency.
- Added a new `BlockData` struct in `block.go` to encapsulate block-related information.
- Refactored the `Commiter` to work with `BlockData` instead of separate block components.
- Updated the `Poller` to use `BlockData` when handling block results.
- Modified storage interfaces to support operations with `BlockData`.
- Simplified data insertion and deletion processes in staging and main storage.
> Separate interface for staging storage

- internal/common/block_failures.go
- internal/storage/clickhouse.go
- internal/storage/memory.go
- internal/tools/clickhouse_create_blocks_table.sql
- internal/tools/clickhouse_create_logs_table.sql
- internal/tools/clickhouse_create_staging_table.sql
- internal/tools/clickhouse_create_traces_table.sql
- internal/tools/clickhouse_create_transactions_table.sql
Implemented block data storage and retrieval functionality, and optimized ClickHouse table configurations.
- Removed `BlockFailureToString` and `StringToBlockFailure` functions from `block_failures.go` as they are unnecessary.
- Implemented `InsertBlockData`, `GetBlockData`, and `DeleteBlockData` methods in both ClickHouse and Memory connectors.
- Added `FINAL` keyword to ClickHouse SELECT queries for improved data consistency. 
- Updated ClickHouse table creation scripts to include `allow_experimental_replacing_merge_with_cleanup` setting. [Read more here](https://clickhouse.com/docs/en/engines/table-engines/mergetree-family/replacingmergetree)
- Added a new SQL script for creating a `block_data` table in the staging schema.
- Modified block and transaction key formats in the Memory …
> Implement block data storage

- internal/orchestrator/commiter.go
- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
- internal/tools/clickhouse_create_logs_table.sql
- internal/tools/clickhouse_create_traces_table.sql
- internal/tools/clickhouse_create_transactions_table.sql
Added support for trace data storage and retrieval in the ClickHouse and Memory connectors.
- Updated the `Commiter` to handle trace data insertion
- Modified the `ClickHouseConnector` and `MemoryConnector` to include `InsertTraces` and `GetTraces` methods
- Added trace-related functionality to the `IMainStorage` interface
- Updated SQL scripts for creating ClickHouse tables, including a new traces table
- Adjusted engine types and order by clauses for better performance in ClickHouse tables
1. Run the updated SQL scripts to create or modify the ClickHouse tables
2. Verify that trace data is being inserted correctly by checking the `traces` table
3. Test the `GetTraces` method to ensure proper retrieval of trace data
4. Confirm that the `Commiter` is successfully handling trace data …
> Add trace processing and optimize ClickHouse table structures

- .gitignore
- api/api.go
- internal/handlers/logs_handlers.go
- internal/handlers/transactions_handlers.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
Updated API response structure, improved query filtering, and added aggregation support for logs.
- Modified `QueryResponse` structure in `api.go` to use `interface{}` for `Data` field and `map[string]string` for `Aggregations`.
- Updated `ParseQueryParams` function to handle `event_name` filter.
- Changed `GroupBy` parameter in `QueryFilter` to accept an array of strings.
- Refactored `GetLogs` function in `clickhouse.go` to support advanced filtering, sorting, and aggregations.
- Updated `IMainStorage` interface to return `QueryResult` instead of `[]common.Log` for `GetLogs`.
- Added debug binary files to `.gitignore`.
1. Run the API and make requests to the logs endpoint with various query parameters.
2. Test filtering using `filter_event_name` and other filter parameters.
3. Verify …
> Implement GetLogs queries without grouping and filter columns

- internal/orchestrator/poller.go
Improved initial block selection logic in the Poller constructor.
Modified the condition for setting the `lastPolledBlock` in the `NewPoller` function. Now, it also checks if the `lastPolledBlock` is less than the `pollFromBlock` configuration value. If true, it resets the `lastPolledBlock` to one block before the `pollFromBlock`.
> Improve initial block setting logic in poller

- internal/orchestrator/committer.go
- internal/orchestrator/failure_recoverer.go
- internal/orchestrator/poller.go
- internal/worker/worker.go
Improved committer performance and added failure recovery mechanisms.
- Increased `DEFAULT_COMMITTER_TRIGGER_INTERVAL` from 250 to 2000 and `DEFAULT_BLOCKS_PER_COMMIT` from 10 to 1000.
- Enhanced logging for better visibility into committer operations.
- Implemented gap detection and failure handling in the committer process.
- Added new Prometheus metrics for tracking gaps and missed blocks.
- Improved the FailureRecoverer to handle block recovery more efficiently.
- Added Prometheus metrics for the FailureRecoverer to track its progress.
- Enhanced the Poller with a new metric to track batch sizes.
1. Run the indexer with the new changes.
2. Monitor the new Prometheus metrics:
- `committer_gap_counter`
- `committer_first_missed_block_number`
- `failure_recoverer_last_triggered_block`
- …
> Fill gaps when detected at the begining of a commit batch

- internal/metrics/metrics.go
- internal/orchestrator/committer.go
- internal/orchestrator/failure_recoverer.go
- internal/orchestrator/poller.go
- internal/worker/worker.go
Centralized Prometheus metrics in a new package and updated references across the codebase.
- Created a new `metrics` package in `internal/metrics/metrics.go`
- Moved all Prometheus metric definitions to the new package
- Updated references to metrics in `committer.go`, `failure_recoverer.go`, `poller.go`, and `worker.go`
- Removed local metric definitions from individual files
1. Ensure all existing metrics are still being recorded correctly
2. Verify that the application compiles and runs without errors
3. Check that Prometheus is able to scrape the metrics as before
4. Confirm that no metrics are duplicated or missing
This change improves code organization and maintainability by:
1. Centralizing all metric definitions in one location
2. Reducing code duplication
3. Making it easier to …
> Encapsulate porometheus metrics in a package

- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
This PR addresses several issues and makes improvements to the poller and storage components:
1. Poller Adjustment:
- Modified the `NewPoller` function to correctly include the first block when `ForceFromBlock` is enabled.
2. ClickHouseConnector Updates:
- Changed the `StoreBlockFailures` method to store the failure time as a Unix timestamp.
- Updated the `scanBlockFailure` function to:
- Convert the timestamp back to a `time.Time` object.
- Store the failure count as an `int` instead of `uint16`.
These changes improve the accuracy of block polling and enhance the consistency of data storage and retrieval in the ClickHouse database.
> Adjust block polling logic and improve ClickHouse data handling

- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Implemented range-based block number retrieval in the poller and storage components.
- Modified `GetLastStagedBlockNumber` function to accept a `rangeEnd` parameter in both ClickHouse and Memory connectors.
- Updated the `Poller` to use the new `untilBlock` parameter when retrieving the last staged block number.
- Added a range check in the Memory connector to ensure the returned block number is within the specified range.
- Adjusted the ClickHouse query to include a range condition when `rangeEnd` is provided.
1. Set different values for `Poller.UntilBlock` in the configuration.
2. Run the poller and verify that it correctly retrieves the last staged block number within the specified range.
3. Test with both ClickHouse and Memory storage to ensure consistent behavior.
4. Verify that the …
> Add range end parameter to GetLastStagedBlockNumber

- internal/common/block.go
- internal/common/log.go
- internal/common/trace.go
- internal/common/transaction.go
- internal/storage/clickhouse.go
- internal/worker/serializer.go
Changed timestamp representation from `time.Time` to `uint64` across multiple structs and functions.
- Modified `Block`, `Log`, `Trace`, and `Transaction` structs to use `uint64` for timestamp fields instead of `time.Time`.
- Updated `ClickHouseConnector` methods to handle `uint64` timestamps directly, removing `time.Unix()` conversions.
- Adjusted `serializeBlock` and `serializeTransaction` functions to work with `uint64` timestamps.
- Removed `hexSecondsTimestampToTime` function as it's no longer needed.
- Removed `time` import from affected files.
1. Run unit tests for affected structs and functions.
2. Perform integration tests with ClickHouse to ensure proper data insertion and retrieval.
3. Verify that timestamp-related operations in the application still work correctly with the new …
> Switch block_time to unix timestamp

- internal/storage/clickhouse.go
Added time package import to clickhouse.go file.
The `time` package from the Go standard library has been imported in the `internal/storage/clickhouse.go` file.
No specific testing is required for this change as it's an import addition. However, ensure that the build process completes successfully and that any existing tests pass without errors.
The addition of the `time` package import suggests that time-related functionality will be used in the clickhouse storage implementation. This could be for handling timestamps, durations, or other time-based operations within the storage layer.
> Add time import to ClickHouse storage module

- internal/metrics/metrics.go
- internal/orchestrator/chain_tracker.go
- internal/orchestrator/orchestrator.go
Implemented a ChainTracker to monitor and report the latest block number in the current chain.
- Added a new `ChainHead` metric in `metrics.go` to track the latest block number.
- Created a new `chain_tracker.go` file with a `ChainTracker` struct and associated methods.
- The `ChainTracker` polls the RPC at regular intervals to fetch the latest block number.
- Updated the `Orchestrator` to start the `ChainTracker` alongside other components.
1. Run the indexer with the new changes.
2. Monitor the `chain_tracker_chain_head` metric using Prometheus or a similar monitoring tool.
3. Verify that the metric is updating at regular intervals (default: every 5 minutes).
4. Compare the reported chain head with the actual latest block number on the blockchain to ensure accuracy.
This change allows …
> Add chain tracker to track chain head

- internal/orchestrator/committer.go
Improved gap handling in the Committer to handle cases where the service crashes before managing to store a block failure for the block 
- Extracted gap handling logic into a new `handleGap` function.
- Enhanced gap detection to store block failures for missing blocks.
- Updated logging to provide more detailed information about detected gaps.
- Modified the error message in case of a gap to include both expected and actual block numbers.
1. Simulate a scenario where there's a gap in block numbers.
2. Verify that the `handleGap` function is called and processes the gap correctly.
3. Check that block failures are stored for missing blocks.
4. Confirm that metrics are updated (GapCounter and MissedBlockNumbers).
5. Validate that the log messages provide accurate information about the …
> Improve gap detection and handling in committer

- cmd/api.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
Updated API documentation and added basic authentication.
- Removed unnecessary contact information and terms of service from API documentation
- Added license information to Swagger documentation
- Updated host and base path in Swagger configuration
- Implemented basic authentication for API endpoints
- Updated Swagger info with version, title, and description
1. Run the API server
2. Access the Swagger documentation at `/swagger/index.html`
3. Verify that the updated information is displayed correctly
4. Test API endpoints using basic authentication
This change improves the API documentation by removing unnecessary information and adding important details like licensing. It also enhances security by implementing basic authentication for API endpoints, ensuring that only authorized users …
> Update Swagger documentation and add BasicAuth

- internal/tools/clickhouse_create_block_failures_table.sql
- internal/tools/clickhouse_create_blocks_table.sql
- internal/tools/clickhouse_create_logs_table.sql
- internal/tools/clickhouse_create_staging_table.sql
- internal/tools/clickhouse_create_traces_table.sql
- internal/tools/clickhouse_create_transactions_table.sql
Removed database prefixes from table names in ClickHouse SQL scripts and updated engine type for logs table.
- Removed database prefixes (`orchestrator.`, `base.`, and `staging.`) from all table names in ClickHouse SQL creation scripts.
- Changed the engine for the `logs` table from `SharedReplacingMergeTree` to `ReplacingMergeTree`. Shared is only available in hosted version and will be applied automatically if you create a ReplacingMergeTree
1. Execute the updated SQL scripts in a ClickHouse environment.
2. Verify that tables are created without database prefixes.
3. Confirm that the `logs` table is created with the `ReplacingMergeTree` engine.
4. Ensure that all other table structures and settings remain unchanged.
- Removing database prefixes allows for more flexibility in table …
> Remove database prefixes from ClickHouse table creation scripts

- cmd/api.go
Added a new endpoint to serve Swagger JSON file.
- Introduced a new GET route `/json` in the API.
- This route serves the `swagger.json` file located in the `./docs` directory.
1. Start the API server.
2. Make a GET request to `http://your-api-host/json`.
3. Verify that the response is the contents of the `swagger.json` file.
This change allows direct access to the Swagger JSON file, which can be useful for:
- Integrating with external tools that consume Swagger/OpenAPI specifications.
- Enabling developers to easily download and use the API documentation offline.
- Facilitating automated testing or documentation generation processes that require the raw Swagger JSON.
> Add Swagger JSON endpoint

- internal/metrics/metrics.go
- internal/orchestrator/poller.go
- internal/worker/worker.go
Added a new metric for the last triggered block in the poller and improved block number tracking.
Removed the division by 10, because this should be configured in Grafana settings to not display scientific notation
- Introduced a new Prometheus gauge metric `poller_last_triggered_block` to track the last block number that triggered the poller.
- Updated the `Poller.Start()` method to set the new metric with the end block number of each polling cycle.
- Modified the `Worker.Run()` method to use `Float64()` instead of dividing by 10 when setting the `LastFetchedBlock` metric, addressing a TODO and improving precision.
1. Run the application and ensure it starts without errors.
2. Check Prometheus metrics to verify the new `poller_last_triggered_block` metric is present and updating …
> Add poller last triggered block metric and improve block number handling

- cmd/api.go
- cmd/root.go
- configs/config.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
Added configurable API host for Swagger documentation and improved API configuration.
- Introduced a new `APIConfig` struct in `configs/config.go` with a `Host` field.
- Added a new command-line flag `--api-host` in `cmd/root.go` with a default value of "localhost:3000".
- Updated `cmd/api.go` to set the Swagger host dynamically using the configured API host.
- Removed the hardcoded host from `docs/docs.go`, `docs/swagger.json`, and `docs/swagger.yaml`.
1. Run the API with a custom host:
```
./indexer api --api-host example.com:8080
```
2. Check the Swagger documentation to ensure the host is set correctly.
This change allows for greater flexibility in deploying the API to different environments. By making the API host configurable, it becomes easier to adapt the service to various …
> Add configurable API host and update Swagger documentation

- cmd/api.go
Makes /openapi.json return the same as /swagger/docs.json
- Modified the `/openapi.json` endpoint to dynamically serve Swagger documentation.
- Replaced static file serving with dynamic generation of Swagger documentation.
1. Start the API server.
2. Navigate to the `/openapi.json` endpoint.
3. Verify that the Swagger documentation is served correctly.
This change improves the flexibility and reliability of Swagger documentation serving. By dynamically generating the documentation, it ensures that the API always serves the most up-to-date version without relying on static files. The added error handling also improves the robustness of the API, providing clear feedback if there are issues with the Swagger documentation.
> Update Swagger documentation handling in the API

- internal/orchestrator/committer.go
- internal/orchestrator/failure_recoverer.go
- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
Refactored data insertion process to allow the storage decide how to handle batched data. 
E.g sql databases can use transactions and concurrency whereas memory storage can do everything sequentially
- Introduced a new `InsertDataForBlocks` method in the `IMainStorage` interface.
- Removed individual insert methods for blocks, transactions, logs, and traces from the interface.
- Implemented `InsertDataForBlocks` in both ClickHouseConnector and MemoryConnector.
- Updated the Committer to use the new `InsertDataForBlocks` method instead of `saveDataToMainStorage`.
- Renamed insert methods in ClickHouseConnector and MemoryConnector to be private.
> Refactor data insertion logic 

- internal/common/block.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
- internal/storage/redis.go
- internal/tools/clickhouse_create_cursors_table.sql
- internal/tools/clickhouse_create_staging_table.sql
Added support for chain reorganization detection and handling in the storage layer.
- Introduced a new `BlockHeader` struct in `block.go`
- Added methods to `ClickHouseConnector` for managing reorg checks and block headers
- Implemented `GetLastReorgCheckedBlockNumber` and `SetLastReorgCheckedBlockNumber` in storage connectors
- Added `LookbackBlockHeaders` and `DeleteDataForBlocks` methods to `IMainStorage` interface
- Updated `MemoryConnector` to support new reorg-related operations
- Added reorg check functionality to `RedisConnector`
- Created a new SQL script for a `cursors` table in ClickHouse
- Modified the staging table creation script to remove the primary key
> Create storage functions for handling reorgs

- cmd/orchestrator.go
- internal/orchestrator/chain_tracker.go
- internal/orchestrator/committer.go
- internal/orchestrator/failure_recoverer.go
- internal/orchestrator/orchestrator.go
- internal/orchestrator/poller.go
- internal/orchestrator/reorg_handler.go
- internal/rpc/rpc.go
- internal/worker/worker.go
Refactored RPC client interface and updated related components for improved modularity and testability.
- Introduced `IRPCClient` interface in `rpc.go` to abstract RPC client functionality.
- Updated `Client` struct to implement `IRPCClient` interface.
- Modified `Initialize()` function to return `IRPCClient` instead of `*Client`.
- Refactored `Orchestrator`, `ChainTracker`, `Committer`, `FailureRecoverer`, `Poller`, `ReorgHandler`, and `Worker` to use `IRPCClient` interface.
- Moved `GetLatestBlockNumber()` method from `Poller` to `Client`.
- Updated method calls and field accesses throughout the codebase to use the new interface.
1. Ensure indexing works after the refactoring.
This refactoring improves the codebase by:
1. Enhancing modularity and separation of concerns.
2. Facilitating …
> Refactor RPC client to use interface

- internal/common/transaction.go
- internal/rpc/serializer.go
- internal/storage/clickhouse.go
- internal/tools/clickhouse_create_blocks_table.sql
- internal/tools/clickhouse_create_logs_table.sql
- internal/tools/clickhouse_create_traces_table.sql
- internal/tools/clickhouse_create_transactions_table.sql
Optimized ClickHouse table structures for improved query performance and data organization.
- Changed order by to include block number, because most queries would be ordering by time (equivalent to block numbers) or fetching a specific block data by number, not by hash
- Introduced a `function_selector` column in the transactions table
- Indexing every log topic to be able to query based on them
1. Apply the SQL changes to a test ClickHouse instance
2. Verify that the tables are created successfully
3. Insert sample data into each table
4. Run queries using the new indexes and ordering to ensure improved performance
5. Compare query execution times with the previous table structure
These changes aim to:
1. Enhance query performance by using more appropriate index types (e.g., bloom_filter …
> Optimize ClickHouse table schemas and indexing

- internal/orchestrator/poller.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
- test/mocks/MockIStagingStorage.go
Improved block polling logic and updated storage interfaces for more precise block range handling.
- Modified `Poller` initialization to handle `ForceFromBlock` configuration more effectively.
- Updated `GetLastStagedBlockNumber` method in storage interfaces to include a `rangeStart` parameter.
- Adjusted ClickHouse and memory storage implementations to support the new `rangeStart` parameter.
- Updated mock storage interface to reflect the changes in the `GetLastStagedBlockNumber` method.
1. Verify that the poller initializes correctly with different `ForceFromBlock` configurations.
2. Test the `GetLastStagedBlockNumber` method with various range start and end values.
3. Ensure that the ClickHouse and memory storage implementations correctly filter blocks within the specified range.
4. …
> Improve poller block range handling and staging data retrieval

- .github/workflows/docker-release.yml
Updated Docker image tagging strategy in the release workflow.
- Modified the tagging logic for the Docker image in the `docker-release.yml` workflow.
- Changed the condition for the `latest` tag to be applied only when the workflow is manually triggered.
- Added a new tag using semantic versioning pattern.
1. Manually trigger the workflow to verify the `latest` tag is applied.
2. Create a new release with a semantic version (e.g., v1.2.3) to confirm the new versioning tag is correctly applied.
3. Check the Docker registry to ensure the images are tagged as expected.
This change provides more control over when the `latest` tag is applied and introduces semantic versioning for better version management of Docker images. It allows for more precise tracking of image versions and ensures the …
> Update Docker image tagging in release workflow

- internal/orchestrator/reorg_handler.go
- internal/orchestrator/reorg_handler_test.go
Added support for handling duplicate blocks during chain reorganization detection.
- Added a check in `findReorgEndIndex` to skip blocks with the same block number during reorg detection
- Added test cases to verify handling of duplicate blocks and correct block sequences
- Improved reorg detection logic to handle unmerged blocks in the chain
1. Run the new test cases:
- `TestHandleReorgWithDuplicateBlocks`
- `TestNothingIsDoneForCorrectBlocks`
2. Verify that duplicate blocks are properly handled and don't trigger false reorg detections
3. Confirm that correct block sequences continue to work as expected
When processing block headers, duplicate blocks with the same block number can appear if there are multiple committers running by mistake. Usually clickhouse will merge these duplicates …
> Skip unmerged blocks in reorg handler

- internal/orchestrator/committer.go
- internal/orchestrator/committer_test.go
- internal/orchestrator/reorg_handler_test.go
Added duplicate block handling in the committer and comprehensive test coverage for the committer component.
- Added logic to skip duplicate blocks in the sequential block processing
- Created new test file `committer_test.go` with extensive test coverage
- Added test cases for duplicate block handling, gap detection, and committer functionality
- Renamed reorg handler test to avoid naming conflicts
1. Run the test suite with `go test ./internal/orchestrator`
2. Verify all committer tests pass, including:
- Duplicate block handling
- Sequential block processing
- Gap detection
- Committer initialization
- Block commit operations
The committer component previously lacked test coverage and could start filling gaps when encountering duplicate blocks. This change improves reliability by …
> Skip duplicate blocks in committer

- internal/orchestrator/committer.go
- internal/orchestrator/committer_test.go
- internal/orchestrator/poller.go
Changed block gap handling to poll missing blocks instead of marking them as failures.
- Replaced the block failure recording mechanism in `handleGap` with a new polling approach
- Created a new `BoundlessPoller` that can poll arbitrary block ranges
- Refactored the `Poller` to extract common functionality into `BoundlessPoller`
- Updated tests to reflect the new polling behavior
1. Run the indexer with a gap in block sequence
2. Verify that missing blocks are now polled and processed
3. Confirm that blocks are properly indexed instead of being marked as failures
4. Run unit tests to verify the new gap handling behavior
The previous implementation would mark missing blocks as failures without attempting to retrieve them. This new approach actively tries to fetch and process missing …
> Poll missing blocks in gap handler

- internal/storage/clickhouse.go
Improved handling of topic values in the `getTopicValueFormat` function.
- Modified the `getTopicValueFormat` function to handle empty topic strings.
- Updated the logic for processing non-empty topics:
- Now uses `ethereum.FromHex` to convert the topic to bytes
- ⚠️ prev. used `ethereum.HexToAddress` was wrong in this context cause topics are not necessarily addresses)
- Ensures the byte slice is exactly 32 bytes by left-padding with zeros.
- Converts the padded bytes to a hash and returns the hexadecimal representation.
1. Test the function with an empty string input to ensure it returns an empty string.
2. Test with various non-empty topic strings, including:
- Short strings (less than 32 bytes)
- Exactly 32-byte strings
- Strings longer than 32 bytes
3. Verify that the output is …
> Don't cut bytes from non-address topics + account for empty topics

- internal/handlers/transactions_handlers.go
- internal/rpc/serializer.go
- internal/storage/clickhouse.go
Implemented signature lookup for transactions and improved query filtering.
- Activated signature lookup in `GetTransactionsByContractAndSignature` function
- Exported `ExtractFunctionSelector` function
- Updated ClickHouse queries to include function selector for transactions
- Generalised signature clause handling for both logs and transactions in ClickHouse queries
1. Make a GET request to `/{chainId}/transactions/{to}/{signature}` endpoint with a valid contract address and function signature
```
curl --location 'http://localhost:3000/660279/transactions/0x6e55472109e6abe4054a8e8b8d9edffcb31032c5/setMinDstGas(uint16,uint16,uint256)?limit=1' \
--header 'Authorization: Basic ...'
```
2. Verify that the returned transactions are filtered correctly based on the provided signature
```json
{ …
```
> Enable transactions look-up by signatures

- internal/common/utils.go
- internal/handlers/logs_handlers.go
- internal/handlers/transactions_handlers.go
Added functionality to strip and normalize Solidity function and event signatures.
- Introduced a new `StripPayload` function in `utils.go` to remove parameter names, 'indexed' keywords, and extra whitespaces from Solidity function or event signatures.
- Implemented helper functions `parseParameters`, `cleanType`, and `isType` to support the signature stripping process.
- Updated `GetLogsByContractAndSignature` and `GetTransactionsByContractAndSignature` handlers to use the new `StripPayload` function before processing requests.
1. Call the API endpoints for getting logs or transactions by contract and signature.
2. Use various Solidity function and event signatures, including those with parameter names, `indexed` keywords, and extra whitespaces.
3. Verify that the API correctly handles …
> Strip signature params

- internal/storage/clickhouse.go
Updated the DELETE query syntax in ClickHouse to use lightweight DELETE FROM instead of ALTER TABLE DELETE.
Modified the query string in the `deleteBatch` function to use `DELETE FROM` syntax instead of `ALTER TABLE DELETE` when removing data from ClickHouse tables.
1. Execute delete operations on ClickHouse tables
2. Verify that records are successfully deleted
3. Check that the operation completes without any syntax errors
The `ALTER TABLE DELETE` syntax is deprecated in newer versions of ClickHouse. Using `DELETE FROM` is the standard and recommended approach for delete operations, ensuring better compatibility and maintainability.
> use lightweight deletes

- internal/orchestrator/poller.go
Improved error handling and logging for blockchain polling operations
- Added a new `ErrNoNewBlocks` error type to explicitly handle cases when no new blocks are available
- Updated error logging to suppress errors when no new blocks are found
- Enhanced the `reachedPollLimit` function to handle nil block numbers
- Modified `getNextBlockRange` to return `ErrNoNewBlocks` instead of nil when no blocks are available
1. Run the poller with a blockchain that has no new blocks
2. Verify that no error messages appear in the logs
3. Test with nil block numbers to ensure proper handling
4. Verify that polling continues normally when new blocks become available
The previous implementation would log errors for expected scenarios (like no new blocks being available), creating unnecessary noise in the …
> Fix edge case where existing range end block causes crashes

- internal/common/utils.go
Fixed Solidity type checking by using string prefix matching for integer types.
Replaced explicit mapping of integer types (uint8, int16, etc.) with a prefix check for "uint" and "int". Non-integer types like address, bool, and string remain in the map.
1. Test type checking with various integer types (uint8, int256, etc.)
2. Verify that non-integer types (address, bool, string) are still correctly identified
3. Ensure negative cases (non-types) return false
The previous implementation listed every possible integer type explicitly, which was verbose and harder to maintain. Uints and ints can be in 8 byte increments.
> fix invalid safeguard for solidity types

- internal/orchestrator/committer.go
Added a limit to the number of blocks that can be polled when handling gaps in block sequences.
- Added a check to limit the number of missing blocks to poll based on the poller's `blocksPerPoll` configuration
- Reordered logging statements for better clarity
- Added debug logging to indicate when block polling is limited due to configuration
1. Configure a low `blocksPerPoll` value
2. Create a scenario with a large gap between expected and actual block numbers
3. Verify that the number of polled blocks is capped at the configured `blocksPerPoll` value
4. Check debug logs to confirm the limitation message appears
To prevent potential performance issues and resource exhaustion when handling large gaps in block sequences. This change ensures the system maintains stability by limiting the …
> do not poll more than the configured amount when filling gaps

- internal/common/abi.go
- internal/common/transaction.go
- internal/common/transaction_test.go
- internal/handlers/transactions_handlers.go
Added transaction data decoding functionality for transactions when a function signature is provided.
- Introduced new ABI parsing utilities to handle function signatures
- Added support for decoding transaction input data using parsed ABI
- Created a new `DecodedTransaction` type that includes the original transaction data along with decoded parameters
- Enhanced transaction handlers to decode transaction data when a function signature is provided
1. Make a request to `/{chainId}/transactions/{contractAddress}/{signature}`
2. Verify that the response includes decoded transaction data with:
- Function name
- Function signature
- Decoded input parameters as key-value pairs
3. Test with various function signatures, including those with complex parameter types (tuples, arrays)
4. Verify that …
> Add transaction data decoding support

- api/api.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/common/abi.go
- internal/common/log.go
- internal/common/log_test.go
- internal/common/transaction.go
- internal/handlers/logs_handlers.go
- internal/handlers/transactions_handlers.go
Added event decoding functionality for Ethereum logs, enabling the parsing and interpretation of indexed and non-indexed event parameters.
- Added `ConstructEventABI` function to parse event signatures into ABI format
- Implemented log decoding functionality to handle both indexed and non-indexed event parameters
- Created new `DecodedLog` and `DecodedLogData` structures to represent decoded event data
- Enhanced log handlers to support automatic event decoding when a signature is provided
- Added support for converting various data types (bytes, numerics) to hexadecimal format
1. Make a GET request to `/{chainId}/events/{contract}/{signature}` with a valid event signature
2. Verify that the response includes decoded event data with:
- Event name and signature
- Indexed parameters …
> decode events

- internal/orchestrator/reorg_handler.go
- internal/storage/clickhouse.go
Added block range validation and optimized block header queries to prevent unnecessary reorg checks.
- Added validation to skip reorg checks when the most recent and last checked block numbers are equal
- Modified the `LookbackBlockHeaders` query to include a lower bound on block numbers, creating a specific range for querying
- Enhanced logging to better indicate when reorg checks are skipped
1. Run the system with chain monitoring enabled
2. Verify logs show skipped reorg checks when blocks are equal
3. Confirm block header queries return results only within the specified range
4. Validate that reorg detection still functions correctly for actual reorgs
The previous implementation would perform unnecessary reorg checks when block numbers were identical and could potentially query more …
> Fix force range for reorg checks

- internal/storage/clickhouse.go
Fixed incorrect string slicing in ClickHouse filter parameters for 'gte' and 'lte' conditions.
Modified the string slicing length in `addFilterParams` function from `-3` to `-4` for 'gte' and 'lte' suffixes to properly extract the base column name from filter parameters.
1. Execute queries using filters with 'gte' and 'lte' suffixes
2. Verify that the generated SQL queries contain the correct column names
3. Confirm that filter conditions are properly applied to the results
The previous implementation was incorrectly slicing the column names for 'gte' and 'lte' conditions, which could lead to malformed SQL queries. This fix ensures proper column name extraction and maintains consistency with the filter parameter naming convention.
> fix: substring correctly

- internal/common/utils.go
Added support for `toStartOfDay` and `toDate` functions in the allowed functions map.
Added two new date-related functions (`toStartOfDay` and `toDate`) to the `allowedFunctions` map, enabling their use within the application.
1. Use the `toStartOfDay` function in expressions to convert a timestamp to the start of its day
2. Use the `toDate` function to convert timestamps to date format
3. Verify that both functions execute without permission errors
To enable date manipulation capabilities within the application, allowing users to perform date-based operations and transformations when working with timestamp data.
> Allow toStartOfDay and toDate functions in the API

- internal/common/utils.go
Added support for the `concat` function in the allowed functions list.
Added the `concat` function to the `allowedFunctions` map, enabling string concatenation operations.
1. Use the `concat` function in your queries or templates
2. Verify that the function executes without permission errors
3. Confirm that string concatenation works as expected
String concatenation is a fundamental operation needed for data manipulation and string formatting. Adding the `concat` function provides users with the ability to combine strings dynamically within their queries or templates.
> whitelist concat function

- internal/common/block.go
- internal/common/log.go
- internal/common/set.go
- internal/common/trace.go
- internal/common/transaction.go
- internal/storage/clickhouse.go
Improved the deletion logic in case of reorgs in ClickHouse by implementing partition-aware deletes and disabling lightweight delete synchronization.
- Added `lightweight_deletes_sync` setting (value 0) to ClickHouse configuration. This will make the deletes async, so processing does not need to wait for it to finish
- Split generic `deleteBatch` function into specific delete functions for blocks, logs, transactions, and traces, which will improve performance due to having all of the order by keys defined
- Implemented two-step deletion process:
1. Query for existing records that need deletion
2. Execute targeted deletes using partition values and primary keys
- Added proper error handling and batch processing for deletions
The previous deletion method was inefficient and could cause …
> improve delete performance for clickhouse

- internal/common/utils.go
- internal/storage/clickhouse.go
Added new time-based functions to the allowed functions map: `toStartOfMonth`, `toStartOfHour`, and `toStartOfMinute`
Added support for ordering aggregation results
Extended the `allowedFunctions` map to include three new time manipulation functions:
- `toStartOfMonth`: Truncates a timestamp to the start of its month
- `toStartOfHour`: Truncates a timestamp to the start of its hour
- `toStartOfMinute`: Truncates a timestamp to the start of its minute
To provide more granular time-based aggregation options for queries, allowing users to group and analyze data at month, hour, and minute levels alongside the existing day-level functionality.
> allow more date functions and ordering for aggregations

- internal/orchestrator/reorg_handler.go
- internal/orchestrator/reorg_handler_test.go
Improved reorg handler block range calculation to support both forward and backward scanning based on the current sync state.
- Added `getReorgCheckRange` function to dynamically determine the block range for reorg checks
- When catching up (large gap between latest checked and committed blocks), the handler scans forward
- When caught up (small gap), the handler looks backward from the latest committed block
- Added protection to prevent negative block numbers when scanning backward
- Added early exit when the latest checked block equals the target block
- Run the new test cases:
- `TestReorgHandlerRangeIsForwardLookingWhenItIsCatchingUp`
- `TestReorgHandlerRangeIsBackwardLookingWhenItIsCaughtUp`
- `TestReorgHandlerRangeStartIs0WhenRangeIsLargerThanProcessedBlocks`
- Verify the reorg …
> make reorg handling backward looking if it has caught up with the chain

- cmd/api.go
- internal/handlers/blocks_handlers.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
- test/mocks/MockIMainStorage.go
Added a new `/blocks` endpoint to retrieve block data with filtering, sorting, and aggregation capabilities.
- Created a new `/blocks` endpoint in the API
- Implemented block data retrieval with support for:
- Filtering by chain ID and other block parameters
- Sorting and pagination
- Aggregation functions
- Group by operations
- Updated the storage interface to return QueryResult for block operations
- Added block scanning functionality to handle database rows
1. Start the API server
2. Make GET requests to `/blocks` with optional query parameters:
- `chainId`: Specify the blockchain network
- `filter`: Apply filters to block data
- `sort_by`: Sort results by specific fields
- `sort_order`: Choose ascending or descending order
- `page` and `limit`: Control pagination
- `aggregate`: Apply …
> feat: get blocks API handle

- internal/storage/clickhouse.go
- internal/storage/connector.go
- test/mocks/MockIMainStorage.go
Updated the GetTraces function to return a QueryResult type instead of a raw array of traces.
- Modified the GetTraces function signature to return `QueryResult[common.Trace]` instead of `[]common.Trace`
- Extracted trace scanning logic into a separate `scanTrace` function
- Updated the GetTraces implementation to use the generic `executeQuery` function
- Updated the mock storage interface to reflect the new return type
1. Verify that existing trace queries continue to work as expected
2. Ensure that pagination and filtering functionality works correctly with traces
3. Confirm that the mock storage interface is properly implemented in test cases
This change brings consistency to the codebase by making the GetTraces function return the same QueryResult type as other query functions. This …
> Conform getTraces to api standard

- internal/tools/clickhouse_create_token_balances_mv.sql
Added validation checks for token balance materialized view to ensure data integrity.
Added additional WHERE clause conditions in the token balances SQL query to validate that:
- `topic_2` and `topic_3` are not empty
- `ids_length` equals `amounts_length`
1. Execute the materialized view creation query
2. Verify that only logs with non-empty `topic_2` and `topic_3` are processed
3. Confirm that logs where `ids_length` matches `amounts_length` are included
4. Check that malformed logs are properly filtered out
To prevent processing of invalid or malformed log entries that could lead to incorrect token balance calculations. This ensures data consistency and accuracy in the materialized view.
> improve token balances mv

- internal/orchestrator/committer.go
- internal/orchestrator/committer_test.go
Added safeguards and tracking for committed block numbers in the Committer component.
- Added `lastCommittedBlock` field to track the highest block number committed in memory
- Renamed `pollFromBlock` to `commitFromBlock` for clarity
- Added validation to prevent processing when max block number from storage is less than last committed block
- Updated block number metrics to use the highest block number from the committed batch
- Added comprehensive test cases for various block number scenarios
To prevent potential data inconsistencies and improve block tracking accuracy. This change ensures the committer maintains a reliable record of processed blocks and handles edge cases where storage and memory states might differ.
> Track  last committed block in memory

- internal/common/block.go
- internal/common/log.go
- internal/common/transaction.go
- internal/handlers/blocks_handlers.go
- internal/handlers/logs_handlers.go
- internal/handlers/transactions_handlers.go
Creates a `Serialize` function for each entity in the common package which makes it easier to reuse in other endpoints
> move entity serialization into common package

- cmd/api.go
- cmd/root.go
- configs/config.go
- configs/secrets.example.yml
- internal/handlers/search_handlers.go
- internal/handlers/search_handlers_test.go
- internal/rpc/rpc.go
- test/mocks/MockIRPCClient.go
Implements a search endpoint
* For a numeric value, tries to fetch a block
* For a hash value (length 66 with 0x) tries to fetch a block, a transaction and logs by signature. Whichever returns data first will be returned
* For a hash value (length 10) fetches transactions with that function selector
* For addresses, uses RPC to check for code. If not configured, looks at latest transactions and determines if it's a contract or not. 
For EOAs returns last 20 initiated transactions
For contracts returns last 20 received transactions
> search endpoint

- internal/common/block.go
- internal/handlers/search_handlers_test.go
Renames `hash` -> `block_hash`, `number` -> `block_number` and `timestamp` -> `block_timestamp` for the block API to have a more uniform naming schema
> rename block fields in api

- internal/tools/clickhouse_create_token_balances_mv.sql
Added support for ERC1155 token amount parsing in token balance materialized view
Updated the token balance calculation logic to properly handle ERC1155 token amounts by parsing the data field when it contains batch transfer information (130 characters). For ERC1155 transfers, it now extracts the amount from the appropriate position in the data field, defaulting to 1 if not present.
ERC1155 tokens can transfer multiple tokens in a single transaction. The previous implementation treated all ERC1155 transfers as single unit transfers, which was incorrect for batch transfers. This change ensures accurate token balance tracking for ERC1155 tokens.
> fix erc1155 single transfers materialized view

- internal/common/log.go
- internal/common/transaction.go
Updated JSON field names to follow consistent snake_case convention and added backward compatibility for deprecated fields.
- Renamed `decodedData` to `decoded` in transaction and log responses
- Changed `indexedParams` to `indexed_params` and `nonIndexedParams` to `non_indexed_params`
- Added deprecated versions of the params fields to maintain backward compatibility
- Added swagger documentation tags to mark deprecated fields
1. Make API requests that fetch decoded logs and transactions
2. Verify new snake_case fields contain the expected data
3. Confirm deprecated camelCase fields still work and contain the same data
4. Check swagger documentation reflects the deprecated status of old fields
To establish consistent snake_case naming conventions across the API while ensuring existing …
> remove camelcase from api responses

- cmd/api.go
- internal/handlers/token_handlers.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
@iuwqyir
- Added the balances endpoint w/out type in path
- Added support for token_ids param in balances and holders endpoints (e.g., "1,2,3")
- Made token type optional for balances endpoint, so you can get all tokens
> feat: support token id in balances and holders endpoints

- internal/common/abi.go
- internal/handlers/logs_handlers.go
- internal/handlers/transactions_handlers.go
Improved signature handling for logs and transactions by moving ABI construction into the main handler functions.
- Consolidated log and transaction handler logic by moving signature processing into the main handler functions
- Updated signature hash calculation to use ABI-generated IDs instead of manual Keccak256 hashing
- Simplified function signatures by removing unnecessary parameter passing
- Improved error handling for ABI construction
1. Query event logs with a valid event signature
- `GET /{chainId}/events/{contract}/{signature}`
2. Query transactions with a valid function signature
- `GET /{chainId}/transactions/{to}/{signature}`
3. Verify that signature hashes are correctly generated from ABIs
4. Confirm that error handling works for invalid signatures
The previous …
> fix signature handling

- internal/handlers/token_handlers.go
Added `token_type` field to the `HolderModel` struct and included it in the serialization function.
We need it to properly detect token types for NFTs handlers, specifically for further metadata resolutions.
- Added a new `TokenType` field to the `HolderModel` struct with JSON tag `token_type` and ClickHouse tag `token_type`
- Updated the `serializeHolder` function to populate the new `TokenType` field from the `holder.TokenType` value
1. Make a request to an endpoint that returns token holder data
2. Verify that the response now includes the `token_type` field in the JSON output
3. Check that the value matches the expected token type for the given token
This change enhances the token holder API response by including the token type information, which allows clients to distinguish between …
> feat: include token type to response

- cmd/api.go
- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/handlers/token_handlers.go
Added a new API endpoint to retrieve token IDs by type for a specific contract address.
- Added a new API endpoint `GET /{chainId}/tokens/{address}` to retrieve token IDs by type (ERC721 or ERC1155) for a specific token address
- Created a new `TokenIdModel` struct to represent token ID data in the response
- Updated Swagger documentation to include the new endpoint and model
- Fixed a parameter location in the documentation for the token holders endpoint (changed `token_type` from path to query parameter)
- Added serialisation functions for token IDs
1. Start the API server
2. Make a GET request to `/{chainId}/tokens/{address}` with the following parameters:
- `token_type`: Optional filter for token type (erc721 or erc1155)
- `hide_zero_balances`: Boolean to filter out zero balances
- …
> feat: tokens route for getting IDs

- .github/workflows/docker-release.yml
- .github/workflows/format.yml
- .github/workflows/test.yml
Pin GitHub Actions to specific commit hashes for improved security and stability.
Updated all GitHub Actions in workflow files to use pinned commit hashes instead of version tags:
- `actions/checkout` pinned to `11bd71901bbe5b1630ceea73d27597364c9af683` (v4.2.2)
- `docker/setup-buildx-action` pinned to `b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2` (v3.10.0)
- `docker/login-action` pinned to `74a5d142397b4f367a81961eba4e8cd7edddf772` (v3.4.0)
- `docker/metadata-action` pinned to `902fa8ec7d6ecbf8d84d538b9b233a880e428804` (v5.7.0)
- `docker/build-push-action` pinned to `471d1dc4e07e5cdedd4c2171150001c434f0b7a4` (v6.15.0)
- `actions/setup-go` pinned to `f111f3307d8850f501ac008e886eec1fd1932a34` (v5.3.0)
Run the GitHub workflows to verify they continue to function as expected:
- Trigger a test …
> fix ci actions with commit hash

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/common/block.go
- internal/common/transaction.go
Updated numeric field types to strings for better precision and updated openapi schema
- Generated openapi for a new API endpoint `/{chainId}/transfers` for retrieving token transfers with various filtering options
- Added a new `TransferModel` definition to support the token transfers endpoint
- Changed several numeric field types from `integer` to `string` in API models to better handle large numbers:
- In `BlockModel`: `gas_limit` and `gas_used`
- In `TransactionModel`: `value`, `gas_price`, `max_fee_per_gas`, `max_priority_fee_per_gas`, `effective_gas_price`, and `blob_gas_price`
1. Make a GET request to the new endpoint `/{chainId}/transfers` with appropriate filters
2. Verify the response contains token transfer data in the expected format
3. Check that numeric values are properly …
> fix serialized types causing overflow

- internal/orchestrator/committer.go
- internal/orchestrator/committer_test.go
- internal/orchestrator/reorg_handler.go
- internal/orchestrator/reorg_handler_test.go
- internal/rpc/rpc.go
- internal/rpc/serializer.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
- test/mocks/MockIMainStorage.go
- test/mocks/MockIStagingStorage.go
Refactored BlockData handling to use value types instead of pointers for slices, improving code clarity and reducing unnecessary pointer indirection.
This PR changes the signature of several functions across the codebase to use value types for slices instead of pointers to slices. Specifically:
- Changed `*[]common.BlockData` to `[]common.BlockData` in function parameters and return types
- Changed `*[]common.Block`, `*[]common.Transaction`, `*[]common.Log`, and `*[]common.Trace` to their value counterparts
- Updated all related function calls and implementations to match the new signatures
- Simplified nil checks by using `len()` directly on slices instead of checking for nil pointers first
- Updated mock implementations to reflect these changes
- Run the existing test suite to ensure …
> do not pass around pointers to slices and maps

- internal/orchestrator/reorg_handler.go
- internal/orchestrator/reorg_handler_test.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
- internal/storage/memory.go
- test/mocks/MockIMainStorage.go
Enhanced `DeleteBlockData` to return deleted block data, enabling better handling of reorgs.
Modified the `DeleteBlockData` method in the storage interface to return the deleted block data:
- Updated the method signature in `IMainStorage` interface to return `([]common.BlockData, error)`
- Implemented the new functionality in `ClickHouseConnector` to collect and return deleted data
- Modified the individual delete methods (`deleteBlocks`, `deleteLogs`, etc.) to return the deleted entities
- Updated the `MemoryConnector` implementation to match the new interface
- Fixed the mock implementation to support the new signature
- Updated the caller in `ReorgHandler` to handle the new return value
1. Run unit tests to verify the updated interface implementations
2. Test a reorg scenario to ensure …
> return block data when deleting it

- cmd/api.go
- internal/common/utils.go
- internal/handlers/transactions_handlers.go
- internal/storage/clickhouse.go
- internal/storage/connector.go
Added a new API endpoint to retrieve all transactions (incoming and outgoing) for a specific wallet address.
- Added a new `/wallet-transactions` endpoint in the API router
- Created a new handler function `GetWalletTransactions` with appropriate Swagger documentation
- Implemented wallet address filtering in the query builder by adding `WalletAddress` field to the `QueryFilter` struct
- Added a new helper function `createWalletAddressClause` that filters transactions where the wallet is either the sender or receiver
1. Make a GET request to `/{chainId}/wallet-transactions?wallet_address=0x...` with a valid wallet address
2. Verify that the response includes both incoming and outgoing transactions for the specified wallet
3. Test with additional query parameters like pagination, sorting, …
> get wallet transcations endpoint

- internal/storage/clickhouse.go
Fixed wallet address filtering in ClickHouse queries to handle empty wallet addresses.
Modified the `createWalletAddressClause` function in `internal/storage/clickhouse.go` to return an empty string when the wallet address is empty, preventing invalid SQL clauses from being generated.
1. Make a query to the API that would normally filter by wallet address, but provide an empty wallet address
2. Verify that the query executes successfully without SQL errors
3. Confirm that results are returned without wallet address filtering applied
When an empty wallet address was provided to the query builder, it would generate an invalid SQL clause like `(from_address = '' OR to_address = '')`. This change prevents SQL errors by not adding the wallet address filter when the address is empty, making the …
> fix: transactions query

- internal/storage/clickhouse.go
Fixed pagination offset calculation in token balances query.
Modified the offset calculation in the `GetTokenBalances` method to use `qf.Page * qf.Limit` instead of `(qf.Page - 1) * qf.Limit`. This changes how pagination works when retrieving token balances from the ClickHouse database.
1. Query token balances with pagination parameters (page > 0, limit > 0)
2. Verify that the correct records are returned for each page
3. Check that there is no overlap or gap between consecutive pages
The previous calculation assumed page numbers started at 1, but params in insight-service use pages starting with `0`. This fix ensures that the correct offset is calculated when paginating through token balances, preventing duplicate records or skipped entries when navigating through pages.
> fix: offset from paging

- docs/docs.go
- docs/swagger.json
- docs/swagger.yaml
- internal/common/log.go
- internal/common/transaction.go
Removed deprecated fields from transaction and log models.
- Removed deprecated fields from transaction and log models:
- Removed `decodedData` field (replaced by `decoded`)
- Removed `indexedParams` and `nonIndexedParams` (replaced by `indexed_params` and `non_indexed_params`)
- Updated Swagger documentation to reflect these changes
Verify the response contains transaction data in the updated format without deprecated fields
This improves API consistency and reduces response payload size by eliminating duplicate data that was previously included for backward compatibility.
> remove deprecated fields

- internal/common/transaction.go
- internal/rpc/serializer.go
- internal/storage/clickhouse.go
- internal/tools/clickhouse_create_transactions_table.sql
Added support for EIP-4844 blob transaction fields in the transaction data model.
- Added two new fields to the `Transaction` struct:
- `MaxFeePerBlobGas` - to store the maximum fee per blob gas
- `BlobVersionedHashes` - to store the versioned hashes of the blobs
- Updated the `TransactionModel` struct to include these new fields
- Modified the transaction serialization logic to handle the new blob-related fields
- Updated the ClickHouse database schema and insertion logic to store the new fields
1. Process transactions from a network that supports EIP-4844 (like Ethereum mainnet post-Dencun upgrade)
2. Verify that blob transactions are correctly stored with their `MaxFeePerBlobGas` and `BlobVersionedHashes` values
3. Query the transactions table to confirm the new fields are populated …
> add blob fields to transactions

- internal/storage/clickhouse.go
Fixed a bug in the `InsertBlockData` function where negative block signs were not being properly handled.
Modified the condition in `InsertBlockData` that determines when to use the block's sign value. Previously, the code would only use the block's sign if it wasn't equal to 1, but now it specifically checks if the sign is -1. This ensures that only explicitly negative signs are treated differently.
1. Insert block data with different sign values (-1, 0, 1)
2. Verify that only blocks with sign = -1 are stored with a negative sign
3. Verify that blocks with sign = 0 are stored with the default sign value of 1
The previous implementation had a logic error where any sign value that wasn't 1 (including 0) would be used as-is. This could lead to incorrect sign values being stored in the …
> fix sign on insert

- internal/common/log.go
- internal/common/transaction.go
- internal/common/utils.go
Added support for converting big numbers to strings in decoded transaction and log data.
- Added a new utility function `ConvertBigNumbersToString` that recursively converts `*big.Int` and `big.Int` values to strings
- Updated the `Serialize` method for `DecodedLog` to convert big numbers to strings in both indexed and non-indexed parameters
- Updated the `Serialize` method for `DecodedTransaction` to convert big numbers to strings in decoded inputs
- Removed unused `StripPayload` function and related helper functions
1. Create a transaction or log that contains big numbers in its decoded data
2. Call the `Serialize` method on the decoded transaction or log
3. Verify that the big numbers are properly converted to strings in the output
Big numbers in decoded transaction and log data need …
> convert decoded big numbers to strings in api response

- internal/storage/clickhouse.go
Added error handling for block data insertion that checks if data was actually inserted despite reported errors.
- Added a new `getMaxBlockNumberConsistent` method that retrieves the maximum block number with sequential consistency guarantees
- Enhanced the `InsertBlockData` error handling to verify if data was actually inserted despite reported errors
- When an error occurs during batch insertion, the code now:
1. Determines the highest block number in the batch
2. Waits briefly (500ms)
3. Checks if the highest block from the batch matches the max consistent block in the database
4. Only returns an error if the verification fails, otherwise logs the error but continues execution
1. Trigger a scenario where ClickHouse reports an error during batch insertion but actually inserts the data …
> handle false positive clickhouse errors during inserts

- internal/rpc/serializer.go
Improved error logging for nil block results in the RPC serializer.
Enhanced the error handling in `SerializeFullBlocks` function by:
1. Including the original error from `rawBlock.Error` in the log message
2. Adding the original error details to the error message returned in the result
1. Trigger a scenario where a nil block result is returned from an RPC call
2. Verify that the logs now include the original error information
3. Confirm that the error message in the result contains the details from the original error
This change provides more detailed error information when nil block results are encountered, making it easier to diagnose issues with RPC calls. The previous implementation only logged that a nil result was received without including the underlying error details, which …
> better logging in case of jsonrpc errors

- internal/storage/clickhouse.go
Added pagination support to the ClickHouse aggregation queries.
Added a LIMIT and OFFSET clause to the GetAggregations method in the ClickHouseConnector. The implementation:
- Adds LIMIT and OFFSET when both page and limit are specified
- Adds only LIMIT when just the limit is specified
- Calculates the correct offset based on page number and limit
1. Make a query to the API that uses the GetAggregations method with pagination parameters
2. Verify that the query returns the correct number of results based on the limit
3. Test with different page numbers to ensure proper pagination
4. Verify that queries without pagination parameters still work correctly
This change enables proper pagination for aggregation queries, which is essential for handling large result sets efficiently. Without …
> limit for aggregations

- internal/common/transaction.go
- internal/common/utils.go
- internal/orchestrator/reorg_handler.go
- internal/rpc/batcher.go
- internal/rpc/params.go
- internal/rpc/rpc.go
- internal/rpc/serializer.go
- internal/worker/worker.go
- test/mocks/MockIRPCClient.go
Added support for fetching transactions by hash through the RPC client.
- Added a new `RawTransaction` type alias in the common package
- Generalized the `RPCFetchBatch` function to `RPCFetchSingleBatch` to work with any key type, not just block numbers
- Added `GetTransactionParams` function to support transaction hash parameters
- Implemented `GetTransactions` method in the RPC client to fetch transactions by hash
- Added `SerializeTransactions` function to convert raw transaction data to the internal format
- Added `Close` method to the `IRPCClient` interface and updated the mock accordingly
1. Fetch transactions using the new method:
```go
client := rpc.NewClient(...)
transactions := client.GetTransactions([]string{"0x123...", "0x456..."})
```
2. Verify that transaction data is …
> add rpc function to fetch transactions by hashes

- internal/handlers/search_handlers_test.go
Improved transaction search test with time-based filtering and updated mock expectations.
- Enhanced `TestSearch_TransactionHash` to properly test time-based transaction searches:
- Added three distinct mock expectations for different time ranges (past 5 days, 5-30 days, and more than 30 days)
- Added timestamp filter parameter validation in mock matchers
- Replaced generic mock calls with more specific expectations for block and log searches
- Updated mock syntax from `.On()` to `.EXPECT()` in address and function signature tests for consistency
Run the test suite to verify that the transaction search functionality works correctly with the time-based filtering:
```
go test ./internal/handlers -v
```
The previous test implementation didn't properly validate time-based transaction …
> fix race condition in tests

- api/api.go
- internal/handlers/blocks_handlers.go
- internal/handlers/logs_handlers.go
- internal/handlers/search_handlers.go
- internal/handlers/token_handlers.go
- internal/handlers/transactions_handlers.go
- internal/handlers/transfer_handlers.go
- internal/storage/clickhouse.go
Changed `Data` and `Aggregations` fields in `QueryResponse` to be pointers to ensure consistent JSON serialization with empty arrays.
- Modified the `QueryResponse` struct in `api/api.go` to use pointer types for `Data` and `Aggregations` fields
- Updated all handler implementations to properly assign values to these pointer fields
- Ensured aggregations are initialized as empty arrays rather than nil to maintain consistent JSON output
- Fixed data assignment in various handlers (blocks, logs, transactions, tokens, transfers) to work with the new pointer types
1. Make API requests that return empty result sets and verify JSON responses include empty arrays (`[]`) instead of omitting fields
2. Test endpoints that return aggregations to ensure they properly serialize
3. Verify that all …
> return data or aggregations as empty array if no results
